
name: nidhika_chat_app
description: A WhatsApp-style chat app using Flutter and Firebase
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.0.3
  flutter_webrtc: ^0.9.34
  permission_handler: ^11.0.0
  image_picker: ^1.0.0

flutter:
  uses-material-design: true
